//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Baiko_PrivateAds
{
    using System;
    using System.Collections.Generic;
    
    public partial class Posts
    {
        public int ID_post { get; set; }
        public Nullable<int> ID_user { get; set; }
        public Nullable<System.DateTime> Date_public { get; set; }
        public string City { get; set; }
        public string Category { get; set; }
        public string Type { get; set; }
        public Nullable<int> ID_status { get; set; }
        public string Name_post { get; set; }
        public string Description { get; set; }
        public string Photo { get; set; }
        public Nullable<long> Cost { get; set; }
        public string Admin_comm { get; set; }
    
        public virtual Statuses Statuses { get; set; }
        public virtual Users Users { get; set; }
    }
}
